services:
    ScyLabs\ApimoBundle\Services\ApimoService:
        arguments: ['@service_container','@doctrine.orm.entity_manager']
    ScyLabs\ApimoBundle\Controller\ApiController:
        arguments: ['@scy_labs_apimo.apimo']
